import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  parseManifest, liveEntries, blobKey, latestKey, manifestKey,
  SCHEMA_VERSION, SCOPE_RULE, ENTRY_STATES,
} from "./types";
import { courseFolderName } from "./folders";

// The worker and this plugin ship as a pair. These fixtures are generated by
// the Go types (internal/manifest/contract_test.go) and read here, so a change
// on either side that breaks the other fails a test instead of a vault.
const schema = (name: string) =>
  readFileSync(fileURLToPath(new URL(`../../schema/${name}`, import.meta.url)), "utf8");

interface StoreContract {
  schema_version: number;
  scope_rule: string;
  states: string[];
  keys: {
    course_id: number;
    run_id: string;
    sha256: string;
    latest_key: string;
    manifest_key: string;
    blob_key: string;
  }[];
}

const isDate = (s: string | undefined) => s !== undefined && !Number.isNaN(Date.parse(s));

describe("store contract generated by the Go worker", () => {
  const c = JSON.parse(schema("store-contract.json")) as StoreContract;

  it("agrees on the schema version", () => expect(SCHEMA_VERSION).toBe(c.schema_version));
  it("agrees on the scope rule name", () => expect(SCOPE_RULE).toBe(c.scope_rule));
  it("knows exactly the worker's entry states", () => expect([...ENTRY_STATES]).toEqual(c.states));
  it("has key cases", () => expect(c.keys.length).toBeGreaterThan(0));

  for (const k of c.keys) {
    it(`builds the worker's keys for course ${k.course_id}`, () => {
      expect(latestKey(k.course_id)).toBe(k.latest_key);
      expect(manifestKey(k.course_id, k.run_id)).toBe(k.manifest_key);
      expect(blobKey(k.sha256)).toBe(k.blob_key);
    });
  }
});

describe("manifest written by the Go worker", () => {
  const m = parseManifest(schema("manifest-golden.json"));

  it("parses", () => {
    expect(m.schema_version).toBe(SCHEMA_VERSION);
    expect(m.entries.length).toBeGreaterThan(0);
  });

  it("carries the course code and name the plugin names folders with", () => {
    expect(typeof m.course_code).toBe("string");
    expect(m.course_code).not.toBe("");
    expect(courseFolderName(m)).toBe("CS3103 [2610] (93794)");
  });

  it("covers every entry state", () => {
    expect(new Set(m.entries.map((e) => e.state))).toEqual(new Set(ENTRY_STATES));
  });

  it("carries the fields the plugin reads, with the types it expects", () => {
    for (const e of m.entries) {
      expect(typeof e.path, e.path).toBe("string");
      expect(typeof e.size, e.path).toBe("number");
      expect(typeof e.canvas_id, e.path).toBe("number");
      expect(isDate(e.updated_at), e.path).toBe(true);
      if (e.state === "stored") expect(e.sha256, e.path).toMatch(/^[0-9a-f]{64}$/);
      if (e.state === "locked") expect(isDate(e.unlock_at), e.path).toBe(true);
      if (e.state === "deleted") expect(isDate(e.deleted_at), e.path).toBe(true);
    }
  });

  it("includes a skip deferred by a scoped pull", () => {
    expect(m.entries.some((e) => e.state === "skipped" && e.rule_name === SCOPE_RULE)).toBe(true);
  });

  it("liveEntries drops exactly the tombstones", () => {
    const live = liveEntries(m);
    expect(live.some((e) => e.state === "deleted")).toBe(false);
    expect(live).toHaveLength(m.entries.filter((e) => e.state !== "deleted").length);
  });
});

describe("manifests the Go worker also rejects", () => {
  const f = JSON.parse(schema("manifest-invalid.json")) as {
    cases: { _why: string; manifest: unknown }[];
  };

  it("has cases", () => expect(f.cases.length).toBeGreaterThan(0));

  for (const [i, c] of f.cases.entries()) {
    it(`rejects ${i}: ${c._why}`, () => {
      expect(() => parseManifest(JSON.stringify(c.manifest))).toThrow(/stele-pull:/);
    });
  }
});
