import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseManifest, Entry, SCOPE_RULE } from "./types";
import { preview, PreviewItem } from "./preview";
import type { FileRecord } from "./state";
import type { Policy } from "./policy";

// Classifies the manifest the Go worker actually writes (generated by
// internal/manifest/contract_test.go), so the panel stays right as the worker
// learns new outcomes.
const golden = parseManifest(
  readFileSync(fileURLToPath(new URL("../../schema/manifest-golden.json", import.meta.url)), "utf8"),
);

const OPEN: Policy = { version: 1, default: "include", rules: [] };
const NOTHING_WRITTEN: Record<string, FileRecord> = {};

function expected(e: Entry): PreviewItem["action"] | undefined {
  switch (e.state) {
    case "deleted": return undefined;
    case "stored": return "download";
    case "locked": return "locked";
    case "failed": return "unavailable";
    case "skipped": return e.rule_name === SCOPE_RULE ? "deferred" : "skip-worker";
  }
}

describe("preview of the manifest the worker writes", () => {
  const p = preview(golden, OPEN, NOTHING_WRITTEN);
  const byPath = new Map(p.items.map((i) => [i.entry.path, i]));

  it("classifies every entry by what this vault should do", () => {
    for (const e of golden.entries) {
      expect(byPath.get(e.path)?.action, e.path).toBe(expected(e));
    }
  });

  it("shows a scoped-pull deferral as pending, not as withheld by a rule", () => {
    const deferred = p.items.filter((i) => i.action === "deferred");
    expect(deferred.length).toBe(p.deferred);
    expect(p.deferred).toBeGreaterThan(0);
    for (const i of deferred) expect(i.entry.rule_name).toBe(SCOPE_RULE);
  });

  it("surfaces the worker's note on a stored file", () => {
    const noted = p.items.filter((i) => i.entry.state === "stored" && i.entry.reason);
    expect(noted.length).toBeGreaterThan(0);
    for (const i of noted) expect(i.reason).toContain(i.entry.reason);
  });

  it("keeps the note on a file this vault already has", () => {
    const e = golden.entries.find((x) => x.state === "stored" && x.reason)!;
    const written = { [e.path]: { sha256: e.sha256!, size: e.size, writtenAt: 0 } };
    const item = preview(golden, OPEN, written).items.find((i) => i.entry.path === e.path)!;
    expect(item.action).toBe("have");
    expect(item.reason).toContain(e.reason);
  });

  it("offers a recorded file again once it is missing from the vault", () => {
    const e = golden.entries.find((x) => x.state === "stored" && !x.reason)!;
    const written = { [e.path]: { sha256: e.sha256!, size: e.size, writtenAt: 0 } };

    const present = preview(golden, OPEN, written).items.find((i) => i.entry.path === e.path)!;
    expect(present.action).toBe("have");

    const gone = preview(golden, OPEN, written, new Set([e.path])).items.find((i) => i.entry.path === e.path)!;
    expect(gone.action).toBe("restore");
    expect(gone.reason).toMatch(/missing from the vault/);
  });

  it("applies local rules with the manifest's course id", () => {
    const local: Policy = {
      version: 1, default: "include",
      rules: [{ name: "not-on-this-device", priority: 1, action: "skip", match: { course_ids: [golden.course_id] } }],
    };
    const q = preview(golden, local, NOTHING_WRITTEN);
    expect(q.toDownload).toBe(0);
    expect(q.skippedLocal).toBe(golden.entries.filter((e) => e.state === "stored").length);
  });
});
